CREATE ROLE gerente WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:B0Eo5ndmeioy4rjj+4vwwA==$UN66lpxmvRQs3+fXimVeJydHM0GD8EedTz8uA6yWTfA=:AcCMaKkd/1e9bD82H6sio6CWzX5sAhIyzATnW6/aFOI=';
  
CREATE ROLE atendente WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  REPLICATION;